window:
  decorations: buttonless
font:
  size: 17
  normal:
    family: Iosevka
    style: Regular
  bold:
    family: Iosevka
    style: Bold
  italic:
    family: Iosevka
    style: Italic
colors:
  primary:
    background: '#32302f'
    foreground: '#ebdbb2'
  normal:
    black:   '#1d1f21'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#d6b48b'
    white:   '#c5c8c6'
  bright:
    black:   '#666666'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#d6b48b'
    white:   '#eaeaea'
env:
  TERM: 'xterm-256color'
